### PR TITLE
Add macro, entrypoint function, and example for permanently-loaded extensions

### PR DESCRIPTION
**Pull request by nebkor**
See https://www.sqlite.org/rescode.html#ok_load_permanently; this should help with #11

### CODE REVIEW

**Comment by nebkor** [comment]
As an aside, I thank you for this project and mention this PR here :)

https://crates.io/crates/julid-rs

**Comment by asg017** [comment]
Thanks @nebkor for the contribution, this (and `julid-rs`) looks awesome!

I got sick this week so I'll be out for a few days, but I fully intend to merge this in (and play with julid-rs) when I'm feeling better

**Comment by nebkor** [comment]
No worries, I hope you feel better soon! Thanks for the kind words, and really, thank you for this project; without it, I would not have been able to write the extension so quickly and painlessly (my C is, uh, "rusty").

**Comment by asg017** [comment]
Thank you @nebkor for this contribution!

Though I do want to point out, when I want a SQLite extension to effect all future DB connections, I have found [`sqlite3_auto_extension`](https://www.sqlite.org/c3ref/auto_extension.html) to be useful. That ways users/applications can choose whether or not an extension is always loaded, since `SQLITE_OK_LOAD_PERMANENTLY` seems to just always load it.

I'm pretty surprised `SQLITE_OK_LOAD_PERMANENTLY` even exists - but I guess it's mostly useful for VFSs?

Thanks again for your contribution! Will be putting out a new release shortly

**Comment by asg017** [comment]
This appears in the latest `v0.0.6-alpha.1` release - will release `v0.0.6` when I document all the new features

**Comment by asg017** [comment]
actually my bad, messed up the release - it's now on `v0.0.6-alpha.2`

**Pull request merged**
